# Generated by Django 5.1.7 on 2025-09-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='phone',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
