# Generated by Django 5.1.7 on 2025-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappbot', '0002_alter_conversationstate_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
