# Generated by Django 5.1.7 on 2025-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, default=(('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')), max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
