# Generated by Django 5.1.7 on 2025-03-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
