# Generated by Django 5.1.7 on 2025-04-07 03:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.IntegerField(null=True)),
                ('is_discounted', models.BooleanField(default=False)),
                ('discounted_price', models.IntegerField(null=True)),
                ('active_days', models.IntegerField(null=True)),
                ('renew_after_hours', models.IntegerField(null=True)),
                ('uploads_allowed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionpackage'),
        ),
    ]
