# Generated by Django 5.1.7 on 2025-04-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscriptionpackage_user_subscribed_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_limit',
            field=models.IntegerField(default=0),
        ),
    ]
