# Generated by Django 5.1.7 on 2025-04-07 05:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_free_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscribed_package',
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('uploads_used', models.IntegerField(default=0)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.subscriptionpackage')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
