# Generated by Django 5.1.7 on 2025-04-30 04:58

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userbusiness'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusiness',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.businessImagesPath),
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.businessImagesPath),
        ),
        migrations.AddField(
            model_name='userbusiness',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
