# Generated by Django 5.1.7 on 2025-05-09 04:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userbusiness_banner_userbusiness_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbusiness',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
