# Generated by Django 5.1.7 on 2025-05-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_subscriptionpackage_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='active_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='discounted_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_discounted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='renew_after_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
