# Generated by Django 5.1.7 on 2025-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_package_active_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('spare parts', 'Spare Parts')], max_length=20, null=True),
        ),
    ]
