# Generated by Django 5.1.7 on 2025-06-14 07:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='payment ID'),
            preserve_default=False,
        ),
    ]
