# Generated by Django 5.1.7 on 2025-06-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='phone',
            field=models.CharField(max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(max_length=50, null=True, verbose_name='payment ID'),
        ),
    ]
