# Generated by Django 5.1.7 on 2025-06-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='account_reference',
        ),
        migrations.AddField(
            model_name='payment',
            name='subscription',
            field=models.UUIDField(null=True, verbose_name='subscription (subscription)'),
        ),
    ]
