# Generated by Django 5.1.7 on 2025-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_payment_account_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='vehicle',
            field=models.UUIDField(blank=True, null=True, verbose_name='vehicle (unit published first)'),
        ),
    ]
