# Generated by Django 5.1.7 on 2025-04-03 12:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('listing_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('year_of_make', models.CharField(blank=True, max_length=20, null=True)),
                ('fuel', models.CharField(blank=True, max_length=40, null=True)),
                ('mileage', models.CharField(blank=True, max_length=60, null=True)),
                ('drive', models.CharField(blank=True, max_length=20, null=True)),
                ('transmission', models.CharField(blank=True, max_length=30, null=True)),
                ('engine_capacity', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.CharField(blank=True, max_length=60, null=True)),
                ('usage', models.CharField(blank=True, max_length=20, null=True)),
                ('tradein', models.BooleanField(default=False)),
                ('financing', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField(auto_now=True, null=True)),
                ('package_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehiclemake'),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('vehicle_make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehiclemake')),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='vehicle_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehiclemodel'),
        ),
    ]
