# Generated by Django 5.1.7 on 2025-04-07 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePostingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('free_duration_days', models.IntegerField(default=7)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='was_free_post',
            field=models.BooleanField(default=False),
        ),
    ]
