# Generated by Django 5.1.7 on 2025-04-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
