# Generated by Django 5.1.7 on 2025-04-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='registration_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
