# Generated by Django 5.1.7 on 2025-04-10 12:15

import apps.listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.listings.models.ListingImagePath),
        ),
    ]
