# Generated by Django 5.1.7 on 2025-04-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='availability',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Sold', 'Sold'), ('Reserved', 'Reserved')], default='Available', max_length=50, null=True),
        ),
    ]
