# Generated by Django 5.1.7 on 2025-05-29 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='listings.listing'),
        ),
    ]
