# Generated by Django 5.1.7 on 2025-06-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_pricehistory_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
    ]
