# Generated by Django 5.1.7 on 2025-06-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_is_top'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_published',
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published')], default='draft', max_length=60),
        ),
    ]
