# Generated by Django 5.1.7 on 2025-06-15 11:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_remove_listing_is_published_listing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHireBooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=70, verbose_name='client name')),
                ('phone', models.CharField(max_length=15, verbose_name='client phone number')),
                ('occasion', models.CharField(max_length=50, verbose_name='occasion type')),
                ('vehicle', models.CharField(max_length=60, verbose_name='preferred vehicle')),
                ('occasion_date', models.CharField(max_length=15, verbose_name='occasion date')),
                ('pickup_time', models.CharField(max_length=15, verbose_name='pickup time')),
                ('pickup_location', models.CharField(max_length=255, verbose_name='pickup location')),
                ('additionals', models.TextField(blank=True, null=True, verbose_name='extra specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=70, verbose_name='client name')),
                ('phone', models.CharField(max_length=15, verbose_name='client phone number')),
                ('make', models.CharField(max_length=60, verbose_name='preferred make')),
                ('model', models.CharField(max_length=60, verbose_name='preferred model')),
                ('budget', models.CharField(max_length=60, verbose_name='budget')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='extra specifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
