# Generated by Django 5.1.7 on 2025-06-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_carhirebooking_searchrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemake',
            name='vehicle_type',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
