# Generated by Django 5.1.7 on 2025-06-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_vehiclemake_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'bike')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'bike')], max_length=10, null=True),
        ),
    ]
