# Generated by Django 5.1.7 on 2025-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemake',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=10, null=True),
        ),
    ]
