# Generated by Django 5.1.7 on 2025-06-21 06:11

import apps.listings.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_alter_listing_vehicle_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('expired', 'Expired')], default='draft', max_length=60),
        ),
        migrations.AlterField(
            model_name='listing',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=30, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('sold_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('expires_at', models.DateTimeField(auto_now=True, null=True)),
                ('parts_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.parttype')),
                ('vehicle_make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehiclemake')),
                ('vehicle_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.vehiclemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PartImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.listings.models.PartImagePath)),
                ('spare_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.sparepart')),
            ],
        ),
    ]
