# Generated by Django 5.1.7 on 2025-06-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_parttype_alter_listing_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freepostingmode',
            name='post_duration',
            field=models.IntegerField(default=14),
        ),
    ]
