# Generated by Django 5.1.7 on 2025-06-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_freepostingmode_post_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
