# Generated by Django 5.1.7 on 2025-06-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_alter_listing_expires_at_alter_listing_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('expired', 'Expired')], default='draft', max_length=20),
        ),
    ]
