# Generated by Django 5.1.7 on 2025-06-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_sparepart_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='free_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='condition',
            field=models.CharField(choices=[('brand new', 'Brand New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=20),
        ),
    ]
