# Generated by Django 5.1.7 on 2025-06-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_sparepart_free_post_alter_sparepart_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
