# Generated by Django 5.1.7 on 2025-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_listing_slug_sparepart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='condition',
            field=models.CharField(choices=[('brand new', 'Brand New'), ('used', 'Used'), ('refurbished', 'Refurbished')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('expired', 'Expired')], default='draft', max_length=70),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike'), ('truck', 'Truck')], max_length=70, null=True),
        ),
    ]
