# Generated by Django 5.1.7 on 2025-07-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_alter_sparepart_condition_alter_sparepart_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='title',
            field=models.TextField(),
        ),
    ]
