# Generated by Django 5.1.7 on 2025-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0024_alter_sparepart_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
