# Generated by Django 5.1.7 on 2025-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_alter_sparepart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
