# Generated by Django 5.1.7 on 2025-08-09 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0026_alter_listing_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclemake',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['name']},
        ),
    ]
