# Generated by Django 5.1.7 on 2025-08-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0027_alter_vehiclemake_options_alter_vehiclemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
