# Generated by Django 5.1.7 on 2025-09-04 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0029_listing_latitude_listing_location_listing_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_top',
        ),
        migrations.AddField(
            model_name='listing',
            name='display_type',
            field=models.CharField(blank=True, choices=[('auction', 'Auction'), ('luxury', 'luxury'), ('featured', 'Featured'), ('latest', 'Latest')], max_length=100, null=True),
        ),
    ]
