# Generated by Django 5.1.7 on 2025-09-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0030_remove_listing_is_top_listing_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='carhirebooking',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='upcoming', max_length=60),
        ),
        migrations.AddField(
            model_name='searchrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=60),
        ),
    ]
