# Generated by Django 5.1.7 on 2025-09-13 16:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_carhirebooking_status_searchrequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('starting_price', models.CharField(max_length=30)),
                ('reserve_price', models.CharField(blank=True, max_length=30, null=True)),
                ('buy_now_price', models.CharField(blank=True, max_length=30, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('ended', 'Ended'), ('sold', 'Sold')], default='upcoming', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bidder', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='listings.auction')),
            ],
            options={
                'ordering': ['-amount'],
            },
        ),
    ]
